### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by GuangchenJ** [irasin/Pytorch_WCT#1]
您好，我是一个刚刚接触风格迁移的新人，非常感谢您的代码帮助我理解了这篇论文
但是训练网络的方法在那篇论文中还是比较模糊
所以在我实现本文中存在一些有关于预训练模型的问题：有关您的预训练模型，是您自己训练的还是直接采用了其他的模型？如果采取的其他模型是采用的哪个模型呢？
谢谢

**Comment by GuangchenJ** [comment]
还有个问题，在您的代码中
`

    c_u, c_e, c_v = torch.svd(c_cov)

    # if necessary, use k-th largest eig-value
    k_c = c
    for i in range(c):
        if c_e[i] < 0.00001:
            k_c = i
            break
    c_d = c_e[:k_c].pow(-0.5)

    w_step1 = torch.mm(c_v[:, :k_c], torch.diag(c_d))
    w_step2 = torch.mm(w_step1, (c_v[:, :k_c].t()))
    whitened = torch.mm(w_step2, cf)
`
SVD分解中之后的w_step的计算中是否应该使用矩阵U而非V
原文的公式是

> <a href="https://www.codecogs.com/eqnedit.php?latex=f_cf_c^T=E_cD_cE_c^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f_cf_c^T=E_cD_cE_c^T" title="f_cf_c^T=E_cD_cE_c^T" /></a>

而
> <a href="https://www.codecogs.com/eqnedit.php?latex=A=UEV^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A=UEV^T" title="A=UEV^T" /></a>
> <a href="https://www.codecogs.com/eqnedit.php?latex=A^T=V^TE^TU" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A^T=V^TE^TU" title="A^T=V^TE^TU" /></a>
> <a href="https://www.codecogs.com/eqnedit.php?latex=AA^T=UE^2U^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?AA^T=UE^2U^T" title="AA^T=UE^2U^T" /></a>

而且

><a href="https://www.codecogs.com/eqnedit.php?latex=VE^2V^T=A^TA" target="_blank"><img src="https://latex.codecogs.com/gif.latex?VE^2V^T=A^TA" title="VE^2V^T=A^TA" /></a>

所以这个地方是否有一些问题？

**Comment by irasin** [comment]
您好，谢谢你的关注。

1.关于预训练模型，原论文提到的是以vgg为base的autoencoder，可是参考原作者以及其他人的代码实现，使用的是normalised vgg19的模型，这个模型的预训练数据在pytorch里面是没有被提供的，所以，我采用了https://github.com/pietrocarbo/deep-transfer 里提供的预训练数据。

2.关于SVD，由于covariance matrix是对称矩阵，对它进行特征值分解与奇异值分解是等价的，这个时候，在上面的代码里U与V是相等的，你可以试一下。另外，你所写的公式里的A对应的是原论文的covariance matrix，而不是对应的f，所以U与V对应的都是特征向量矩阵E。

如果有什么不清楚的，欢迎一起探讨。

>

**Comment by GuangchenJ** [comment]
非常感谢

**Comment by irasin** [comment]
您好，我现在正在写pytorch版的[AvatarNet](https://arxiv.org/abs/1805.03857)，如果有兴趣的话，我们可以合作吗？

**Comment by GuangchenJ** [comment]
非常感谢您的赏识，但是我只是一个刚刚学习风格迁移和pytorch的新人，您的代码质量非常高，我害怕会耽误您的进度，因此我打算先学习一阵子之后再进行一些复现工作。但是我非常希望之后能够跟您合作，谢谢。

**Comment by irasin** [comment]
您多虑了，我也是最近才开始学习这些东西，纯粹只是感兴趣自己做着玩的，非常希望有感兴趣的朋友可以一起做这方面的复现，如果你有空或者感兴趣的话，请随时联系我。

**Comment by GuangchenJ** [comment]
好的，非常感谢
