### ISSUE TITLE
alpha shouldn't be an integer ?

### ISSUE THREAD

**Issue by dmaugis** [irasin/Pytorch_WCT#2]
it seems to me you cannot use test.py with alpha as a float
but
colored_feature = alpha * colored_feature + (1 - alpha) * content_feature
should be

colored_feature = alpha * colored_feature + (1.0 - alpha) * content_feature

and alpha should be float.

no ?

**Comment by irasin** [comment]
Hi, @dmaugis 

Yes, indeed. Alpha should be a float and I have fixed it.

Thanks a lot.
